#
# Github Setup
#
name: Test Package

on:
  workflow_dispatch:

jobs:

  #
  # Jobs
  #
  Job_A:
    name: Run Unit Test
    runs-on: RoVaMx
    steps:

      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Run unit test
        shell: bash
        run: |
         fastlane test_package

      - name: Prepare Code Coderage Package
        shell: bash
        run: |
          ls -la fastlane/build/x86_64-apple-macosx/debug/codecov
          cp fastlane/build/x86_64-apple-macosx/debug/codecov/RoVa-Log.json fastlane/build/code_coverage.json
          ls -la fastlane/build

      - name: Upload Code Coverage Package  Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: code_coverage_artifact
          path: fastlane/build/code_coverage.json
          if-no-files-found: error

  Job_B_1:
    name: Lines Code Coverage
    runs-on: RoVaMx
    needs: [
      Job_A
    ]
    steps:

      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Download Code Coverage Package Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: code_coverage_artifact
          path: fastlane

      - name: Validate 
        shell: bash
        run: |
          ls -la fastlane
          echo "LINES"
          lines_count=$(jq '.data[0].totals.lines.count' fastlane/code_coverage.json)
          lines_covered=$(jq '.data[0].totals.lines.covered' fastlane/code_coverage.json)
          lines_percent=$(jq '.data[0].totals.lines.percent' fastlane/code_coverage.json)
          echo -e "\t count  : $lines_count"
          echo -e "\t covered: $lines_covered"
          echo -e "\t percent: $lines_percent"
          if [ "$lines_percent" -lt "101" ]; then
            echo -e "\n\t\t FAILED ❌"
          else
            echo -e "\n\t\t PASSED ✅"
          fi

  Job_B_2:
    name: Function Code Coverage
    runs-on: RoVaMx
    needs: [
      Job_A
    ]
    steps:

      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Download Code Coverage Package Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: code_coverage_artifact
          path: fastlane

      - name: Validate 
        shell: bash
        run: |
          ls -la fastlane
          echo "FUNCTIONS"
          func_count=$(jq '.data[0].totals.functions.count' fastlane/code_coverage.json)
          func_covered=$(jq '.data[0].totals.functions.covered' fastlane/code_coverage.json)
          func_percent=$(jq '.data[0].totals.functions.percent' fastlane/code_coverage.json)
          echo -e "\t count  : $func_count"
          echo -e "\t covered: $func_covered"
          echo -e "\t percent: $func_percent"
          if [ "$func_percent" -lt "90" ]; then
            echo -e "\t\t FAILED ❌"
          else
            echo -e "\n\t\t PASSED ✅"
          fi

  Job_B_3:
    name: Instantiations Code Coverage
    runs-on: RoVaMx
    needs: [
      Job_A
    ]
    steps:

      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Download Code Coverage Package Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: code_coverage_artifact
          path: fastlane

      - name: Validate 
        shell: bash
        run: |
          ls -la fastlane
          echo "FUNCTIONS"
          inst_count=$(jq '.data[0].totals.instantiations.count' fastlane/code_coverage.json)
          inst_covered=$(jq '.data[0].totals.instantiations.covered' fastlane/code_coverage.json)
          inst_percent=$(jq '.data[0].totals.instantiations.percent' fastlane/code_coverage.json)
          echo -e "\t count  : $inst_count"
          echo -e "\t covered: $inst_covered"
          echo -e "\t percent: $inst_percent"
          if [ "$inst_percent" -lt "90" ]; then
            echo -e "\t\t FAILED ❌"
          else
            echo -e "\n\t\t PASSED ✅"
          fi


  Job_Completition:
    name: Completition
    runs-on: RoVaMx
    needs: [
      Job_B_1,
      Job_B_2,
      Job_B_3
    ]
    steps:

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
      # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C07DCT33R9U'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "‼️ TestPackage Completed : ${{ job.status }}\n${{ github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}"
                  }
                }
              ]
            }
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  #
  # Fail Jobs
  #
  Job_A_Fail:
    name: Unit Test Fail
    runs-on: RoVaMx
    needs: [
      Job_A
    ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:

      - name: Run unit test
        shell: bash
        run: |
         echo "Running"

  Job_B_1_Fail:
    name: Lines Coverage Fail
    runs-on: RoVaMx
    needs: [
      Job_B_1
    ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:

      - name: Run unit test
        shell: bash
        run: |
         echo "Running"

  Job_B_2_Fail:
    name: Function Coverage Fail
    runs-on: RoVaMx
    needs: [
      Job_B_2
    ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:

      - name: Run unit test
        shell: bash
        run: |
         echo "Running"

  Job_B_3_Fail:
    name: Instantiations Coverage Fail
    runs-on: RoVaMx
    needs: [
      Job_B_3
    ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:

      - name: Run unit test
        shell: bash
        run: |
         echo "Running"
